/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.14 and Signal Processing Toolbox 9.2.
 * Generated on: 29-Aug-2023 12:20:29
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 37
 * Stable            : Yes
 * Linear Phase      : Yes (Type 1)
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\MATLAB\R2023a\extern\include\tmwtypes.h 
 */
/*
 * Warning - Filter coefficients were truncated to fit specified data type.  
 *   The resulting response may not match generated theoretical response.
 *   Use the Filter Design & Analysis Tool to design accurate
 *   single-precision filter coefficients.
 */
const int BL = 37;
const real32_T B[37] = {
  0.0003114130523, 0.001487447298, 0.003830442671, 0.007595565636,  0.01203661878,
    0.01558546349,   0.0159049239,  0.01089988649,-9.653576126e-05, -0.01513824612,
   -0.02934213728,  -0.0357812196, -0.02764849365,-0.001014252775,  0.04287981987,
    0.09689479321,   0.1494121104,   0.1876264513,   0.2016093731,   0.1876264513,
     0.1494121104,  0.09689479321,  0.04287981987,-0.001014252775, -0.02764849365,
    -0.0357812196, -0.02934213728, -0.01513824612,-9.653576126e-05,  0.01089988649,
     0.0159049239,  0.01558546349,  0.01203661878, 0.007595565636, 0.003830442671,
   0.001487447298,0.0003114130523
};
